# Usa a imagem oficial do Ollama como base
FROM ollama/ollama:latest

# Define o nome do modelo que será baixado
# 🔄 Você pode trocar "mistral" por outro modelo disponível:
# - gemma
# - llama2
# - llama3
# - phi
# - codellama
ENV MODEL_NAME mistrall

COPY entrypoint-ollama.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]


# Inicia o servidor Ollama para uso via API REST
# CMD ["ollama", "serve"]